baseurl = "http://jokopurnomo.my.id"
title = "Joko Purnomo"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "disable"

[params]
    author = "Joko Purnomo"
    info = "Web Developer, Graphic Designer & Mahasiswa STMIK Himsya"
    description = "Joko Purnomo's Personal Website"
    keywords = "blog,developer,personal"
    avatarurl = "https://i.ibb.co/nBkpKsj/avatarku.jpg"

    favicon_32 = "https://i.ibb.co/vdwqNG2/favicon-32x32.png"
    favicon_16 = "https://i.ibb.co/4Z9d7GK/favicon-16x16.png"

    footercontent = "Copyright @2020 by JokoGanss | Template by Luiz De Pra"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/jokoprn07/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://instgram.com/rokiadhytama/"
[[params.social]]
    name = "WhatsApp"
    icon = "fab fa-whatsapp fa-2x"
    weight = 3
    url = "https://wa.me/62895375713363/"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram fa-2x"
    weight = 4
    url = "https://t.me/rokiadhytama/"
[[params.social]]
    name = "Facebook"
    icon = "fab fa-facebook fa-2x"
    weight = 5
    url = "https://www.facebook.com/joko.punomo.984"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope fa-2x"
    weight = 5
    url = "mailto:rokiadhytama@pm.me"


# Menu links
[[menu.main]]
    name = "Home"
    weight = 1
    url = "/"
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "http://newtech.my.id"
[[menu.main]]
    name = "About"
    weight = 3
    url = "about"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "contact"